name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*"

jobs:
  tag:
    name: New version tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - uses: ramsey/composer-install@v2
        with:
          composer-options: "--ignore-platform-reqs --optimize-autoloader"

      - name: Build plugin
        run: |
          npm ci --no-progress --no-dev
          npm run build

      - name: Deploy plugin to wordpress.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
