name: Deploy to WordPress.org

on:
    push:
        tags:
            - "*"

jobs:
    tag:
        name: New version tag
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: php-actions/composer@v2

            -   name: Build plugin
                run: |
                    npm install
                    npm run build
                    composer update
                    composer install --no-dev

            -   name: Deploy plugin to wordpress.org
                uses: 10up/action-wordpress-plugin-deploy@stable
                env:
                    SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                    SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
